/*
IamBackoffice Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iambackoffice

import (
	"encoding/json"
)

// checks if the IambackofficeAssignRolesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IambackofficeAssignRolesRequest{}

// IambackofficeAssignRolesRequest struct for IambackofficeAssignRolesRequest
type IambackofficeAssignRolesRequest struct {
	LoginId              *string  `json:"loginId,omitempty"`
	TenantId             *string  `json:"tenantId,omitempty"`
	RoleCodes            []string `json:"roleCodes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IambackofficeAssignRolesRequest IambackofficeAssignRolesRequest

// NewIambackofficeAssignRolesRequest instantiates a new IambackofficeAssignRolesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIambackofficeAssignRolesRequest() *IambackofficeAssignRolesRequest {
	this := IambackofficeAssignRolesRequest{}
	return &this
}

// NewIambackofficeAssignRolesRequestWithDefaults instantiates a new IambackofficeAssignRolesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIambackofficeAssignRolesRequestWithDefaults() *IambackofficeAssignRolesRequest {
	this := IambackofficeAssignRolesRequest{}
	return &this
}

// GetLoginId returns the LoginId field value if set, zero value otherwise.
func (o *IambackofficeAssignRolesRequest) GetLoginId() string {
	if o == nil || IsNil(o.LoginId) {
		var ret string
		return ret
	}
	return *o.LoginId
}

// GetLoginIdOk returns a tuple with the LoginId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IambackofficeAssignRolesRequest) GetLoginIdOk() (*string, bool) {
	if o == nil || IsNil(o.LoginId) {
		return nil, false
	}
	return o.LoginId, true
}

// HasLoginId returns a boolean if a field has been set.
func (o *IambackofficeAssignRolesRequest) HasLoginId() bool {
	if o != nil && !IsNil(o.LoginId) {
		return true
	}

	return false
}

// SetLoginId gets a reference to the given string and assigns it to the LoginId field.
func (o *IambackofficeAssignRolesRequest) SetLoginId(v string) {
	o.LoginId = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *IambackofficeAssignRolesRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IambackofficeAssignRolesRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *IambackofficeAssignRolesRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *IambackofficeAssignRolesRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetRoleCodes returns the RoleCodes field value if set, zero value otherwise.
func (o *IambackofficeAssignRolesRequest) GetRoleCodes() []string {
	if o == nil || IsNil(o.RoleCodes) {
		var ret []string
		return ret
	}
	return o.RoleCodes
}

// GetRoleCodesOk returns a tuple with the RoleCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IambackofficeAssignRolesRequest) GetRoleCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.RoleCodes) {
		return nil, false
	}
	return o.RoleCodes, true
}

// HasRoleCodes returns a boolean if a field has been set.
func (o *IambackofficeAssignRolesRequest) HasRoleCodes() bool {
	if o != nil && !IsNil(o.RoleCodes) {
		return true
	}

	return false
}

// SetRoleCodes gets a reference to the given []string and assigns it to the RoleCodes field.
func (o *IambackofficeAssignRolesRequest) SetRoleCodes(v []string) {
	o.RoleCodes = v
}

func (o IambackofficeAssignRolesRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IambackofficeAssignRolesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LoginId) {
		toSerialize["loginId"] = o.LoginId
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.RoleCodes) {
		toSerialize["roleCodes"] = o.RoleCodes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IambackofficeAssignRolesRequest) UnmarshalJSON(data []byte) (err error) {
	varIambackofficeAssignRolesRequest := _IambackofficeAssignRolesRequest{}

	err = json.Unmarshal(data, &varIambackofficeAssignRolesRequest)

	if err != nil {
		return err
	}

	*o = IambackofficeAssignRolesRequest(varIambackofficeAssignRolesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "loginId")
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "roleCodes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *IambackofficeAssignRolesRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *IambackofficeAssignRolesRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableIambackofficeAssignRolesRequest struct {
	value *IambackofficeAssignRolesRequest
	isSet bool
}

func (v NullableIambackofficeAssignRolesRequest) Get() *IambackofficeAssignRolesRequest {
	return v.value
}

func (v *NullableIambackofficeAssignRolesRequest) Set(val *IambackofficeAssignRolesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIambackofficeAssignRolesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIambackofficeAssignRolesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIambackofficeAssignRolesRequest(val *IambackofficeAssignRolesRequest) *NullableIambackofficeAssignRolesRequest {
	return &NullableIambackofficeAssignRolesRequest{value: val, isSet: true}
}

func (v NullableIambackofficeAssignRolesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIambackofficeAssignRolesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
