/*
IamBackoffice Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iambackoffice

import (
	"encoding/json"
)

// checks if the IambackofficeLoginMfaRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IambackofficeLoginMfaRequest{}

// IambackofficeLoginMfaRequest struct for IambackofficeLoginMfaRequest
type IambackofficeLoginMfaRequest struct {
	TenantId             *string `json:"tenantId,omitempty"`
	Code                 *string `json:"code,omitempty"`
	TwoFactorId          *string `json:"twoFactorId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IambackofficeLoginMfaRequest IambackofficeLoginMfaRequest

// NewIambackofficeLoginMfaRequest instantiates a new IambackofficeLoginMfaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIambackofficeLoginMfaRequest() *IambackofficeLoginMfaRequest {
	this := IambackofficeLoginMfaRequest{}
	return &this
}

// NewIambackofficeLoginMfaRequestWithDefaults instantiates a new IambackofficeLoginMfaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIambackofficeLoginMfaRequestWithDefaults() *IambackofficeLoginMfaRequest {
	this := IambackofficeLoginMfaRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *IambackofficeLoginMfaRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IambackofficeLoginMfaRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *IambackofficeLoginMfaRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *IambackofficeLoginMfaRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *IambackofficeLoginMfaRequest) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IambackofficeLoginMfaRequest) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *IambackofficeLoginMfaRequest) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *IambackofficeLoginMfaRequest) SetCode(v string) {
	o.Code = &v
}

// GetTwoFactorId returns the TwoFactorId field value if set, zero value otherwise.
func (o *IambackofficeLoginMfaRequest) GetTwoFactorId() string {
	if o == nil || IsNil(o.TwoFactorId) {
		var ret string
		return ret
	}
	return *o.TwoFactorId
}

// GetTwoFactorIdOk returns a tuple with the TwoFactorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IambackofficeLoginMfaRequest) GetTwoFactorIdOk() (*string, bool) {
	if o == nil || IsNil(o.TwoFactorId) {
		return nil, false
	}
	return o.TwoFactorId, true
}

// HasTwoFactorId returns a boolean if a field has been set.
func (o *IambackofficeLoginMfaRequest) HasTwoFactorId() bool {
	if o != nil && !IsNil(o.TwoFactorId) {
		return true
	}

	return false
}

// SetTwoFactorId gets a reference to the given string and assigns it to the TwoFactorId field.
func (o *IambackofficeLoginMfaRequest) SetTwoFactorId(v string) {
	o.TwoFactorId = &v
}

func (o IambackofficeLoginMfaRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IambackofficeLoginMfaRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.TwoFactorId) {
		toSerialize["twoFactorId"] = o.TwoFactorId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IambackofficeLoginMfaRequest) UnmarshalJSON(data []byte) (err error) {
	varIambackofficeLoginMfaRequest := _IambackofficeLoginMfaRequest{}

	err = json.Unmarshal(data, &varIambackofficeLoginMfaRequest)

	if err != nil {
		return err
	}

	*o = IambackofficeLoginMfaRequest(varIambackofficeLoginMfaRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "code")
		delete(additionalProperties, "twoFactorId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *IambackofficeLoginMfaRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *IambackofficeLoginMfaRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableIambackofficeLoginMfaRequest struct {
	value *IambackofficeLoginMfaRequest
	isSet bool
}

func (v NullableIambackofficeLoginMfaRequest) Get() *IambackofficeLoginMfaRequest {
	return v.value
}

func (v *NullableIambackofficeLoginMfaRequest) Set(val *IambackofficeLoginMfaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIambackofficeLoginMfaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIambackofficeLoginMfaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIambackofficeLoginMfaRequest(val *IambackofficeLoginMfaRequest) *NullableIambackofficeLoginMfaRequest {
	return &NullableIambackofficeLoginMfaRequest{value: val, isSet: true}
}

func (v NullableIambackofficeLoginMfaRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIambackofficeLoginMfaRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
