/*
IamBackoffice Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iambackoffice

import (
	"encoding/json"
)

// checks if the IambackofficeLogoutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IambackofficeLogoutRequest{}

// IambackofficeLogoutRequest struct for IambackofficeLogoutRequest
type IambackofficeLogoutRequest struct {
	Global               *bool        `json:"global,omitempty"`
	Tokens               *ProtobufAny `json:"tokens,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IambackofficeLogoutRequest IambackofficeLogoutRequest

// NewIambackofficeLogoutRequest instantiates a new IambackofficeLogoutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIambackofficeLogoutRequest() *IambackofficeLogoutRequest {
	this := IambackofficeLogoutRequest{}
	return &this
}

// NewIambackofficeLogoutRequestWithDefaults instantiates a new IambackofficeLogoutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIambackofficeLogoutRequestWithDefaults() *IambackofficeLogoutRequest {
	this := IambackofficeLogoutRequest{}
	return &this
}

// GetGlobal returns the Global field value if set, zero value otherwise.
func (o *IambackofficeLogoutRequest) GetGlobal() bool {
	if o == nil || IsNil(o.Global) {
		var ret bool
		return ret
	}
	return *o.Global
}

// GetGlobalOk returns a tuple with the Global field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IambackofficeLogoutRequest) GetGlobalOk() (*bool, bool) {
	if o == nil || IsNil(o.Global) {
		return nil, false
	}
	return o.Global, true
}

// HasGlobal returns a boolean if a field has been set.
func (o *IambackofficeLogoutRequest) HasGlobal() bool {
	if o != nil && !IsNil(o.Global) {
		return true
	}

	return false
}

// SetGlobal gets a reference to the given bool and assigns it to the Global field.
func (o *IambackofficeLogoutRequest) SetGlobal(v bool) {
	o.Global = &v
}

// GetTokens returns the Tokens field value if set, zero value otherwise.
func (o *IambackofficeLogoutRequest) GetTokens() ProtobufAny {
	if o == nil || IsNil(o.Tokens) {
		var ret ProtobufAny
		return ret
	}
	return *o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IambackofficeLogoutRequest) GetTokensOk() (*ProtobufAny, bool) {
	if o == nil || IsNil(o.Tokens) {
		return nil, false
	}
	return o.Tokens, true
}

// HasTokens returns a boolean if a field has been set.
func (o *IambackofficeLogoutRequest) HasTokens() bool {
	if o != nil && !IsNil(o.Tokens) {
		return true
	}

	return false
}

// SetTokens gets a reference to the given ProtobufAny and assigns it to the Tokens field.
func (o *IambackofficeLogoutRequest) SetTokens(v ProtobufAny) {
	o.Tokens = &v
}

func (o IambackofficeLogoutRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IambackofficeLogoutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Global) {
		toSerialize["global"] = o.Global
	}
	if !IsNil(o.Tokens) {
		toSerialize["tokens"] = o.Tokens
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IambackofficeLogoutRequest) UnmarshalJSON(data []byte) (err error) {
	varIambackofficeLogoutRequest := _IambackofficeLogoutRequest{}

	err = json.Unmarshal(data, &varIambackofficeLogoutRequest)

	if err != nil {
		return err
	}

	*o = IambackofficeLogoutRequest(varIambackofficeLogoutRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "global")
		delete(additionalProperties, "tokens")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *IambackofficeLogoutRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populate the value of well-known types
func (o *IambackofficeLogoutRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableIambackofficeLogoutRequest struct {
	value *IambackofficeLogoutRequest
	isSet bool
}

func (v NullableIambackofficeLogoutRequest) Get() *IambackofficeLogoutRequest {
	return v.value
}

func (v *NullableIambackofficeLogoutRequest) Set(val *IambackofficeLogoutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIambackofficeLogoutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIambackofficeLogoutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIambackofficeLogoutRequest(val *IambackofficeLogoutRequest) *NullableIambackofficeLogoutRequest {
	return &NullableIambackofficeLogoutRequest{value: val, isSet: true}
}

func (v NullableIambackofficeLogoutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIambackofficeLogoutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
